# escape=`

FROM lacledeslan/gamesvr-tf2

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-tf2-freeplay"

HEALTHCHECK NONE

COPY ./dist /app/tf/

COPY ./dist.linux /app/tf/

# UPDATE USERNAME
RUN usermod -l TF2Freeplay TF2

USER TF2Freeplay

WORKDIR /app/
